version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 51515:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - hospital
   pgadmin:
        image: dpage/pgadmin4:latest
        labels:
            name: pgadmin
        ports:
                - '7050:80'
        depends_on:
                - db
        environment:
                PGADMIN_DEFAULT_EMAIL: 'husseinkatana17@gmail.com'
                PGADMIN_DEFAULT_PASSWORD: 'password'
        networks:
        - kadweka
   odoo:
        image: odoo:12.0
        restart: always
        ports:
                - 8149:8069
                - 8072:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - ./custom-addons:/mnt/custom-addons
                - odoo-data:/var/lib/odoo
        networks:
                - hospital
volumes:
        odoo-data:
        db-data:
networks:
        hospital:
#    nginx:
#         image: nginx:latest
#         ports:
#                 - 80:80
#                 - 443:443
#         restart: always
#         depends_on:
#                 - odoo
#         volumes:
#                 - ./nginx/sites-enabled/:/etc/nginx/conf.d:ro
#                 # - /etc/letsencrypt:/etc/letsencrypt:ro
#         networks:
#                 - hospital